In [1]:
# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

### 1. Import the moovies dataset

# https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset

In [2]:
data = pd.read_csv('movie_metadata.csv')

In [3]:
data

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### 2. Use crosstabs to show the number of moovies per country

In [9]:
movies_per_countries = data.pivot_table(index=['country'],values=['movie_title'],aggfunc='count')

In [13]:
pd.set_option('display.max_rows', 65)
movies_per_countries

                      movie_title
country
Afghanistan                     1
Argentina                       4
Aruba                           1
Australia                      55
Bahamas                         1
Belgium                         4
Brazil                          8
Bulgaria                        1
Cambodia                        1
Cameroon                        1
Canada                        126
Chile                           1
China                          30
Colombia                        1
Czech Republic                  3
Denmark                        11
Dominican Republic              1
Egypt                           1
Finland                         1
France                        154
Georgia                         1
Germany                        97
Greece                          2
Hong Kong                      17
Hungary                         2
Iceland                         3
India                          34
Indonesia                       1
Iran                            4
Ireland                        12
Israel                          4
Italy                          23
Japan                          23
Kenya                           1
Kyrgyzstan                      1
Libya                           1
Mexico                         17
Netherlands                     5
New Line                        1
New Zealand                    15
Nigeria                         1
Norway                          8
Official site                   1
Pakistan                        1
Panama                          1
Peru                            1
Philippines                     1
Poland                          5
Romania                         4
Russia                         11
Slovakia                        1
Slovenia                        1
South Africa                    8
South Korea                    14
Soviet Union                    1
Spain                          33
Sweden                          6
Switzerland                     3
Taiwan                          2
Thailand                        5
Turkey                          1
UK                            448
USA                          3807
United Arab Emirates            1
West Germany                    3

In [28]:
pd.crosstab([data.country],aggfunc=[data.movie_title].valuecount())

AttributeError: 'list' object has no attribute 'valuecount'

### 3. Create a crosstab to show the number of films per director and genre splitted by country

In [19]:
pd.crosstab([data.director_name,data.genres], [data.country])

,country,Afghanistan,Argentina,Aruba,Australia,Bahamas,Belgium,Brazil,Bulgaria,Cambodia,Cameroon,...,Spain,Sweden,Switzerland,Taiwan,Thailand,Turkey,UK,USA,United Arab Emirates,West Germany
director_name,genres,,,,,,,,,,,,,,,,,,,,,
A. Raven Cruz,Action|Adventure|Comedy|Fantasy|Sci-Fi,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Hann,Drama|Horror|Mystery|Sci-Fi|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Schneider,Drama|Mystery,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Aaron Seltzer,Comedy|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Abel Ferrara,Crime|Drama,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoran Lisinac,Comedy|Music|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
Álex de la Iglesia,Crime|Mystery|Thriller,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
Émile Gaudreault,Comedy|Drama,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Éric Tessier,Action|Drama|Horror|Thriller,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Étienne Faure,Drama|Musical|Romance,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### 4. Average duration of filmes grouped by color

In [20]:
data.pivot_table(index=['color'],values=['duration'])

                    duration
color
 Black and White  112.253589
Color             107.042908

### 5. Average number of likes per director (assuming that total film's likes are counted as a sum of actor's likes)

In [23]:
data['total_likes']=data['actor_1_facebook_likes']+data['actor_2_facebook_likes']+data['actor_3_facebook_likes']
data.pivot_table(index='director_name',values='total_likes')

                    total_likes
director_name
A. Raven Cruz            1094.0
Aaron Hann                406.0
Aaron Schneider         16970.0
Aaron Seltzer            4598.0
Abel Ferrara             2198.0
...                         ...
Zoran Lisinac             870.0
Álex de la Iglesia        702.0
Émile Gaudreault          917.0
Éric Tessier               72.0
Étienne Faure              19.0

[2385 rows x 1 columns]